;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; FPM Configuration for eLabFTW ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
daemonize = no
error_log = /dev/stderr
; only include our custom pool
include=/run/php/elabpool.conf
