version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    day: friday
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: master
  cooldown:
      default-days: 12
      semver-major-days: 32
      semver-minor-days: 24
      semver-patch-days: 3
  ignore:
  - dependency-name: snyk
    versions:
    - ">= 0"
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    day: friday
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: master
  cooldown:
      default-days: 12
      semver-major-days: 32
      semver-minor-days: 24
      semver-patch-days: 3
- package-ecosystem: uv
  directory: "/containers/chem-plugin"
  cooldown:
      default-days: 12
      semver-major-days: 32
      semver-minor-days: 24
      semver-patch-days: 3
