nodeLinker: pnp
enableGlobalCache: false
cacheFolder: /var/cache/elabftw/yarn/cache
globalFolder: /var/cache/elabftw/yarn/global
installStatePath: /var/cache/elabftw/yarn/install-state.gz
pnpUnpluggedFolder: /var/cache/elabftw/yarn/unplugged
virtualFolder: /var/cache/elabftw/yarn/__virtual__
approvedGitRepositories:
npmMinimalAgeGate: 12d
plugins:
  - ./src/tools/yarn-plugin-tinymce.js
