nodeLinker: pnp
enableGlobalCache: false
cacheFolder: /run/elabftw/yarn/cache
globalFolder: /run/elabftw/yarn/global
installStatePath: /run/elabftw/yarn/install-state.gz
pnpUnpluggedFolder: /run/elabftw/yarn/unplugged
virtualFolder: /run/elabftw/yarn/__virtual__
approvedGitRepositories:
npmMinimalAgeGate: 12d
plugins:
  - ./src/tools/yarn-plugin-tinymce.js
