/* eslint-disable quotes */
/* This file is generated by "bin/console dev:i18n4js" command, DO NOT EDIT directly */
const t = {
  translation: {
    "click-to-edit": "Click to edit",
    "comment-add": "Afegir un comentari",
    "dropzone-upload-area": "Arrossega els fitxers fins aquí per a adjuntar-los",
    "dropzone-filesize-limit": "File size limit:",
    "editing-metadata": "You are currently editing the metadata attached to this entry.",
    "entity-default-title": "Sense títol",
    "entity-delete-warning": "L’element o els elements seleccionats i totes les dades associades s’eliminaran definitivament. Això no es pot desfer. Estàs segur?",
    "extra-fields": "Extra fields",
    "filename": "Nom de l'arxiu",
    "generic-delete-warning": "Eliminar això?",
    "link-delete-warning": "Voleu eliminar aquest enllaç?",
    "new-apikey-warning": "Aquesta és l'única vegada que es mostrarà la clau! Assegureu-vos de copiar-lo en un lloc segur ja que no el podreu tornar a veure:",
    "nothing-selected": "Nothing selected!",
    "now": "Now",
    "please-wait": "Espereu ...",
    "replace-edited-file": "Do you want to replace the file on the server with this edit?",
    "request-filename": "Introduïu el nom del fitxer",
    "step-delete-warning": "Voleu eliminar aquest pas?",
    "step-unfinish-warning": "Are you sure you want to undo this step?",
    "tag-delete-warning": "Vols suprimir aquesta etiqueta?",
    "upload-file-comment": "Comentari d’arxiu",
    "template-title": "Template title",
    "today": "Today",
  },
};
export default t;
