/* eslint-disable quotes */
/* This file is generated by "bin/console dev:i18n4js" command, DO NOT EDIT directly */
const t = {
  translation: {
    "click-to-edit": "Click to edit",
    "comment-add": "Einen Kommentar hinzufügen",
    "dropzone-upload-area": "Dateien zum Hochladen hier fallen lassen",
    "dropzone-filesize-limit": "Begrenzung der Dateigröße:",
    "editing-metadata": "Sie bearbeiten gerade die Metadaten zu diesem Eintrag.",
    "entity-default-title": "Unbenannt",
    "entity-delete-warning": "Die ausgewählten Element(e) und alle zugehörigen Daten werden dauerhaft gelöscht. Das kann nicht rückgängig gemacht werden. Bist du sicher?",
    "extra-fields": "Zusätzliche Felder",
    "filename": "Dateiname",
    "generic-delete-warning": "Element löschen?",
    "link-delete-warning": "Diesen Link löschen?",
    "new-apikey-warning": "This is the only time the key will be shown! Make sure to copy it somewhere safe as you won't be able to see it again:",
    "nothing-selected": "Nichts ausgewählt!",
    "now": "Now",
    "please-wait": "Bitte warten…",
    "replace-edited-file": "Möchten Sie die Datei auf dem Server durch diese Bearbeitung ersetzen?",
    "request-filename": "Geben Sie den Namen der Datei ein",
    "saved": "Gespeichert",
    "step-delete-warning": "Diesen Schritt löschen?",
    "step-unfinish-warning": "Sind Sie sicher, dass Sie diesen Schritt rückgängig machen wollen?",
    "tag-delete-warning": "Tag löschen?",
    "template-title": "Titel der Vorlage",
    "today": "Today",
    "upload-file-comment": "Dateikommentar",
  },
};
export default t;
