/* eslint-disable quotes */
/* This file is generated by "bin/console dev:i18n4js" command, DO NOT EDIT directly */
const t = {
  translation: {
    "click-to-edit": "Click to edit",
    "comment-add": "Añadir un comentario",
    "dropzone-upload-area": "Deje sus archivos aquí para subirlos",
    "dropzone-filesize-limit": "File size limit:",
    "editing-metadata": "You are currently editing the metadata attached to this entry.",
    "entity-default-title": "Sin título",
    "entity-delete-warning": "Los item(s) seleccionados y todo los datos asociados serán permanentemente elilminados. Esto no puede deshacerse. Está seguro?",
    "extra-fields": "Extra fields",
    "filename": "Nombre del archivo",
    "generic-delete-warning": "¿Eliminar esto?",
    "link-delete-warning": "¿Eliminar este enlace?",
    "new-apikey-warning": "This is the only time the key will be shown! Make sure to copy it somewhere safe as you won't be able to see it again:",
    "nothing-selected": "Nothing selected!",
    "now": "Now",
    "please-wait": "Por favor espera…",
    "replace-edited-file": "Do you want to replace the file on the server with this edit?",
    "request-filename": "Ingrese el nombre del archivo",
    "step-delete-warning": "¿Eliminar este paso?",
    "step-unfinish-warning": "Are you sure you want to undo this step?",
    "tag-delete-warning": "Eliminar esta etiqueta?",
    "upload-file-comment": "Comentario de archivo",
    "template-title": "Template title",
    "today": "Today",
  },
};
export default t;
