/* eslint-disable quotes */
/* This file is generated by "bin/console dev:i18n4js" command, DO NOT EDIT directly */
const t = {
  translation: {
    "click-to-edit": "Cliquer pour modifier",
    "comment-add": "Ajouter un commentaire",
    "dropzone-upload-area": "Déposez ici les fichiers à uploader",
    "dropzone-filesize-limit": "Taille limite de fichier :",
    "editing-metadata": "Vous êtes en train de modifier les métadonnées jointes à cette entrée.",
    "entity-default-title": "Sans titre",
    "entity-delete-warning": "Le ou les objet(s) sélectionné(s) ainsi que toutes les données associées seront supprimés définitivement. Cela est irréversible. Êtes-vous sûr(e) ?",
    "extra-fields": "Champs supplémentaires",
    "filename": "Nom du fichier",
    "generic-delete-warning": "Supprimer ça ?",
    "link-delete-warning": "Supprimer ce lien ?",
    "nothing-selected": "Aucune sélection !",
    "now": "Maintenant",
    "please-wait": "Patientez…",
    "replace-edited-file": "Souhaitez-vous remplacer le fichier sur le serveur avec ce changement ?",
    "request-filename": "Nom du fichier",
    "step-delete-warning": "Supprimer cette étape ?",
    "step-unfinish-warning": "Êtes-vous certain(e) de vouloir défaire cette étape ?",
    "tag-delete-warning": "Supprimer ce tag ?",
    "upload-file-comment": "Commentaire du fichier",
    "template-title": "Titre du modèle",
    "today": "Aujourd’hui",
  },
};
export default t;
