/* eslint-disable quotes */
/* This file is generated by "bin/console dev:i18n4js" command, DO NOT EDIT directly */
const t = {
  translation: {
    "click-to-edit": "Click to edit",
    "comment-add": "Tambahkan komentar",
    "dropzone-upload-area": "Taruh berkas di sini untuk mengunggah",
    "dropzone-filesize-limit": "Batas ukuran berkas:",
    "editing-metadata": "Anda sedang menyunting metadata yang dilampirkan ke entri ini.",
    "entity-default-title": "Tanpa Judul",
    "entity-delete-warning": "Komponen terpilih dan data terkait akan dihapus permanen. Ini tidak dapat dibatalkan. Anda yakin?",
    "extra-fields": "Kolom tambahan",
    "filename": "Nama file",
    "generic-delete-warning": "Hapus ini?",
    "link-delete-warning": "Hapus tautan ini?",
    "new-apikey-warning": "This is the only time the key will be shown! Make sure to copy it somewhere safe as you won't be able to see it again:",
    "nothing-selected": "Tidak ada yang dipilih!",
    "now": "Now",
    "please-wait": "Mohon tunggu…",
    "replace-edited-file": "Apakah Anda ingin mengganti file di server dengan hasil edit ini?",
    "request-filename": "Masukkan nama file",
    "step-delete-warning": "Hapus langkah ini?",
    "step-unfinish-warning": "Anda yakin ingin mengurungkan langkah ini?",
    "tag-delete-warning": "Hapus label ini?",
    "upload-file-comment": "File komentar",
    "template-title": "Judul templat",
    "today": "Today",
  },
};
export default t;
