/* eslint-disable quotes */
/* This file is generated by "bin/console dev:i18n4js" command, DO NOT EDIT directly */
const t = {
  translation: {
    "click-to-edit": "Click to edit",
    "comment-add": "Aggiungi un commento",
    "dropzone-upload-area": "Trascina qui i file da allegare",
    "dropzone-filesize-limit": "File size limit:",
    "editing-metadata": "You are currently editing the metadata attached to this entry.",
    "entity-default-title": "Senza titolo",
    "entity-delete-warning": "Quanto è stato selezionato (nonché i dati associati) sarà definitivamente cancellato. Il processo è irreversibile. Si è veramente sicuri?",
    "extra-fields": "Campi addizionali",
    "filename": "Nome del file",
    "generic-delete-warning": "Cancellare questo?",
    "link-delete-warning": "Eliminare questo collegamento?",
    "new-apikey-warning": "Questa è l'unica volta che verrà mostrata la chiave! Assicurati di copiarlo in un posto sicuro perché non potrai più vederlo:",
    "nothing-selected": "Nessuna selezione!",
    "now": "Now",
    "please-wait": "Attendere, prego…",
    "replace-edited-file": "Si vuole rimpiazzare il file sul server con questo?",
    "request-filename": "Inserire il nome del file",
    "step-delete-warning": "Cancellare questo passaggio?",
    "step-unfinish-warning": "Are you sure you want to undo this step?",
    "tag-delete-warning": "Si vuol eliminare questo tag?",
    "upload-file-comment": "Commento sul file",
    "template-title": "Titolo del Modello",
    "today": "Today",
  },
};
export default t;
