/* eslint-disable quotes */
/* This file is generated by "bin/console dev:i18n4js" command, DO NOT EDIT directly */
const t = {
  translation: {
    "click-to-edit": "Click to edit",
    "comment-add": "コメントを追加",
    "dropzone-upload-area": "ここにファイルをドロップしてアップロードします",
    "dropzone-filesize-limit": "File size limit:",
    "editing-metadata": "You are currently editing the metadata attached to this entry.",
    "entity-default-title": "無題",
    "entity-delete-warning": "選択したアイテムとすべての関連データが完全に削除されます。これは、元に戻すことはできません。実行して良いですか？",
    "extra-fields": "Extra fields",
    "filename": "ファイル名",
    "generic-delete-warning": "これを削除しますか？",
    "link-delete-warning": "このリンクを削除しますか？",
    "new-apikey-warning": "This is the only time the key will be shown! Make sure to copy it somewhere safe as you won't be able to see it again:",
    "nothing-selected": "Nothing selected!",
    "now": "Now",
    "please-wait": "お待ちください…",
    "replace-edited-file": "Do you want to replace the file on the server with this edit?",
    "request-filename": "ファイルの名前を入力してください",
    "saved": "保存済み",
    "step-delete-warning": "このステップを削除しますか？",
    "step-unfinish-warning": "Are you sure you want to undo this step?",
    "tag-delete-warning": "このタグを削除しますか？",
    "template-title": "Template title",
    "today": "Today",
    "undefined-group": "Undefined group",
    "upload-file-comment": "ファイルコメント",
  },
};
export default t;
