/* eslint-disable quotes */
/* This file is generated by "bin/console dev:i18n4js" command, DO NOT EDIT directly */
const t = {
  translation: {
    "click-to-edit": "Click to edit",
    "comment-add": "Dodaj komentarz",
    "dropzone-upload-area": "Przeciągnij pliki tutaj aby załadować",
    "dropzone-filesize-limit": "File size limit:",
    "editing-metadata": "You are currently editing the metadata attached to this entry.",
    "entity-default-title": "Bez tytułu",
    "entity-delete-warning": "Wybrany element(y) i wszystkie powiązane z nim dane zostaną nieodwracalnie usunięte. Ta operacja nie może być cofnięta. Jesteś pewny?",
    "extra-fields": "Dodatkowe pola",
    "filename": "Nazwa pliku",
    "generic-delete-warning": "Czy na pewno chcesz to skasować?",
    "link-delete-warning": "Usunąć ten link?",
    "new-apikey-warning": "This is the only time the key will be shown! Make sure to copy it somewhere safe as you won't be able to see it again:",
    "nothing-selected": "Niczego nie wybrano!",
    "now": "Now",
    "please-wait": "Proszę czekać…",
    "replace-edited-file": "Czy chcesz zastąpić plik na serwerze tą edycją?",
    "request-filename": "Wpisz nazwę pliku",
    "step-delete-warning": "Usunąć ten krok?",
    "step-unfinish-warning": "Czy na pewno chcesz cofnąć ten krok?",
    "tag-delete-warning": "Usunąć ten tag?",
    "upload-file-comment": "Komentarz do pliku",
    "template-title": "Tytuł szablonu",
    "today": "Today",
  },
};
export default t;
