/* eslint-disable quotes */
/* This file is generated by "bin/console dev:i18n4js" command, DO NOT EDIT directly */
const t = {
  translation: {
    "click-to-edit": "Click to edit",
    "comment-add": "Adicionar um comentário",
    "dropzone-upload-area": "Arraste aqui os arquivos que quiser anexar ao experimento",
    "dropzone-filesize-limit": "File size limit:",
    "editing-metadata": "You are currently editing the metadata attached to this entry.",
    "entity-default-title": "Sem título",
    "entity-delete-warning": "Os items selecionados e todos os dados associados a eles serão permanentemente deletados. Não vai ter jeito de voltar atrás. Tem certeza?",
    "extra-fields": "Campos extra",
    "filename": "Nome do arquivo",
    "generic-delete-warning": "Deletar isso aqui?",
    "link-delete-warning": "Deletar este link?",
    "new-apikey-warning": "This is the only time the key will be shown! Make sure to copy it somewhere safe as you won't be able to see it again:",
    "nothing-selected": "Nada foi selecionado!",
    "now": "Now",
    "please-wait": "Por favor, aguarde...",
    "replace-edited-file": "Você gostaria de substituir o arquivo no servidor por esta versão editada?",
    "request-filename": "Digite o nome do arquivo",
    "saved": "Alterações salvas",
    "step-delete-warning": "Deletar esta etapa?",
    "step-unfinish-warning": "Tem certeza que gostaria de desfazer esta etapa?",
    "tag-delete-warning": "Deletar esta tag?",
    "template-title": "Título do modelo",
    "today": "Today",
    "upload-file-comment": "Comentário no arquivo",
  },
};
export default t;
