/* eslint-disable quotes */
/* This file is generated by "bin/console dev:i18n4js" command, DO NOT EDIT directly */
const t = {
  translation: {
    "click-to-edit": "Click to edit",
    "comment-add": "Adicionar um comentário",
    "dropzone-upload-area": "Arraste os ficheiros para aqui para os carregar",
    "dropzone-filesize-limit": "File size limit:",
    "editing-metadata": "You are currently editing the metadata attached to this entry.",
    "entity-default-title": "Sem título",
    "entity-delete-warning": "O (s) item (s) selecionado (s) e todos os dados associados serão excluídos permanentemente. Isto não pode ser desfeito. Você tem certeza?",
    "extra-fields": "Campos extra",
    "filename": "Nome do arquivo",
    "generic-delete-warning": "Eliminar isto?",
    "link-delete-warning": "Excluir este link?",
    "new-apikey-warning": "This is the only time the key will be shown! Make sure to copy it somewhere safe as you won't be able to see it again:",
    "nothing-selected": "Nada foi selecionado!",
    "now": "Now",
    "please-wait": "Por favor, espere…",
    "replace-edited-file": "Você gostaria de substituir o arquivo no servidor por esta versão editada?",
    "request-filename": "Insira o nome do arquivo",
    "saved": "Guardado",
    "step-delete-warning": "Excluir este passo?",
    "step-unfinish-warning": "Tem certeza que gostaria de desfazer este passo?",
    "tag-delete-warning": "Excluir esta tag?",
    "template-title": "Título do modelo",
    "today": "Today",
    "undefined-group": "Undefined group",
    "upload-file-comment": "Comentário no arquivo",
  },
};
export default t;
