/* eslint-disable quotes */
/* This file is generated by "bin/console dev:i18n4js" command, DO NOT EDIT directly */
const t = {
  translation: {
    "click-to-edit": "Click to edit",
    "cancel": "Prekliči",
    "comment-add": "Dodaj komentar",
    "dropzone-upload-area": "Za nalaganje povlecite datoteko sem",
    "dropzone-filesize-limit": "File size limit:",
    "editing-metadata": "You are currently editing the metadata attached to this entry.",
    "entity-default-title": "Brez naslova",
    "entity-delete-warning": "Izbrani predmeti in vsi pridruženi podatki bodo trajno izbrisani. Tega ni mogoče razveljaviti. Ali si prepričan?",
    "extra-fields": "Extra fields",
    "filename": "Filename",
    "generic-delete-warning": "Želite izbrisati?",
    "link-delete-warning": "Želite izbrisati to povezavo?",
    "new-apikey-warning": "This is the only time the key will be shown! Make sure to copy it somewhere safe as you won't be able to see it again:",
    "nothing-selected": "Nothing selected!",
    "now": "Now",
    "please-wait": "Please wait…",
    "replace-edited-file": "Do you want to replace the file on the server with this edit?",
    "request-filename": "Enter name of the file",
    "save": "Shrani",
    "saved": "Saved",
    "step-delete-warning": "Ali želite izbrisati ta korak?",
    "step-unfinish-warning": "Are you sure you want to undo this step?",
    "tag-delete-warning": "Želite izbrisati to oznako?",
    "template-title": "Template title",
    "today": "Today",
    "undefined-group": "Undefined group",
    "upload-file-comment": "Komentar datoteke",
  },
};
export default t;
