/* eslint-disable quotes */
/* This file is generated by "bin/console dev:i18n4js" command, DO NOT EDIT directly */
const t = {
  translation: {
    "click-to-edit": "Click to edit",
    "comment-add": "添加评论",
    "dropzone-upload-area": "拖动文件到此处进行上传",
    "dropzone-filesize-limit": "文件大小限制:",
    "editing-metadata": "当前正在编辑附加到此项的元数据。",
    "entity-default-title": "未命名",
    "entity-delete-warning": "所选项目和所有相关数据将被永久删除。这不能被撤销。您确定吗？",
    "extra-fields": "额外字段",
    "filename": "文件名",
    "generic-delete-warning": "删除？",
    "link-delete-warning": "删除此链接？",
    "nothing-selected": "未选中任何选项！",
    "now": "Now",
    "please-wait": "请稍候…",
    "replace-edited-file": "您要用此编辑替换服务器上的文件吗？",
    "request-filename": "输入文件名",
    "step-delete-warning": "删除此步骤？",
    "step-unfinish-warning": "确实要撤消此步骤吗？",
    "tag-delete-warning": "删除这个标签？",
    "upload-file-comment": "档案评论",
    "template-title": "模板标题",
    "today": "Today",
  },
};
export default t;
