networks:
  default:
    name: elabftw-net
services:
  cypress:
    image: elab-cypress
    extra_hosts:
      - "elab.local:host-gateway"
    build:
      context: ../..
      dockerfile: ./containers/cypress/Dockerfile
    container_name: elab-cypress
