networks:
  default:
    name: elabftw-net
    external: true
services:
  cypress:
    image: elabftw/elab-cypress:14.5.4
    extra_hosts:
      - "elab.local:host-gateway"
    container_name: elab-cypress
