[program:gunicorn]
directory=/srv/indigo
command=/bin/bash -c "/srv/indigo/.venv/bin/gunicorn --bind 0.0.0.0:8080 --no-control-socket --workers=$(nproc) app:app"
autostart=true
autorestart=true
user=nobody
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
killasgroup=true
