# circle ci config for elabftw
# https://www.elabftw.net
version: 2.1
# code coverage orb
orbs:
  codecov: codecov/codecov@5.4.3
# split the jobs to run back_end tests and front e2e tests after db setup
executors:
  elab-executor:
    # The following configuration line tells CircleCI to use the specified docker image as the runtime environment for you job.
    # For more information on choosing an image (or alternatively using a
    # VM instead of a container) see https://circleci.com/docs/2.0/executor-types/
    # To see the list of pre-built images that CircleCI provides for most common languages see
    # https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: cimg/base:current
    resource_class: large
    environment:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      COMPOSE_DOCKER_CLI_BUILD: 1

# See https://circleci.com/docs/reusing-config/#authoring-reusable-commands
commands:

  populate_db:
    description: Populate the database
    steps:
      - run:
          name: Populate the database
          command: |
            docker exec elabtmp bin/init db:populate src/tools/populate-config.yml.dist -y --fast

  build_image:
    steps:
      - run:
          name: Build image
          command: |
            docker build -t elabftw/elabimg:ci --build-arg CI=1 -f containers/elabimg/Dockerfile .
            docker build -t elabftw/elabtmp -f containers/elabtmp/Dockerfile .
            docker build -t elabftw/circleci -f containers/circleci/Dockerfile .

  load_image:
    steps:
      - run:
          name: Load image
          command: docker image load -i /tmp/elabftw-circleci.tar

  start_container:
    steps:
      - run:
          name: Start container
          command: docker compose -f containers/circleci/docker-compose.yml up -d --no-build

  start_mysql:
    steps:
      - run:
          name: Start mysql container
          command: docker compose -f containers/mysqltmp/docker-compose.yml up -d --wait --wait-timeout 120

  start_cypress:
    steps:
      - run:
          name: Start cypress container
          command: docker compose -f containers/cypress/docker-compose.yml up -d --no-build

  copy_cypress_tests:
    steps:
      - run:
          name: Copy Cypress tests
          command: |
            docker cp cypress.config.ts elab-cypress:/home/node/cypress.config.ts
            docker cp tsconfig.json elab-cypress:/home/node/tsconfig.json
            docker cp tests/cypress/. elab-cypress:/home/node/tests/cypress/
            docker cp tests/_data/. elab-cypress:/home/node/tests/_data/
            docker exec -u root elab-cypress chown -R node:node /home/node/tests

jobs:
  build_elabtmp_image:
    executor: elab-executor
    working_directory: ~/elabftw/elabftw
    shell: /bin/bash --login
    steps:
      - checkout
      - setup_remote_docker:
          version: docker27
          docker_layer_caching: true
      - build_image
      - run:
          name: Export image
          command: docker image save -o /tmp/elabftw-circleci.tar elabftw/circleci
      - persist_to_workspace:
          root: /tmp
          paths:
            - elabftw-circleci.tar

  code_linters:
    executor: elab-executor
    parallelism: 6
    working_directory: ~/elabftw/elabftw
    shell: /bin/bash --login
    steps:
      - checkout
      - setup_remote_docker:
          version: docker27
      - attach_workspace:
          at: /tmp
      - load_image
      - start_container
      - run:
          name: Run SCSS linter
          command: |
            if [ "$CIRCLE_NODE_INDEX" -eq "0" ]; then
              docker exec elabtmp yarn csslint
            fi
      - run:
          name: Run Javascript linter
          command: |
            if [ "$CIRCLE_NODE_INDEX" -eq "1" ]; then
              docker exec elabtmp yarn jslint
            fi
      - run:
          name: Run PHP-CS-Fixer
          command: |
            if [ "$CIRCLE_NODE_INDEX" -eq "2" ]; then
              docker exec elabtmp yarn phpcs-dry
            fi
      - run:
          name: Run Twig linter
          command: |
            if [ "$CIRCLE_NODE_INDEX" -eq "3" ]; then
              docker exec elabtmp yarn twigcs
            fi
      - run:
          name: Run PSALM
          command: |
            if [ "$CIRCLE_NODE_INDEX" -eq "4" ]; then
              docker exec elabtmp yarn psalm
            fi
      - run:
          name: Run PHPStan
          command: |
            if [ "$CIRCLE_NODE_INDEX" -eq "5" ]; then
              docker exec elabtmp yarn phpstan
            fi

  php_unit_tests:
    executor: elab-executor
    working_directory: ~/elabftw/elabftw
    shell: /bin/bash --login
    steps:
      - checkout
      - setup_remote_docker:
          version: docker27
      - attach_workspace:
          at: /tmp
      - load_image
      - start_container
      - start_mysql
      - populate_db
      - run:
          name: Run API v2 tests
          command: docker exec elabtmp php vendor/bin/codecept run apiv2
      - run:
          name: Run unit tests with coverage
          command: |
            docker exec elabtmp php vendor/bin/codecept run unit \
              --coverage \
              --coverage-xml=coverage.xml \
              --coverage-html=coverage

            docker exec elabtmp test -f /elabftw/tests/_output/coverage.xml
            docker exec elabtmp \
              tar -C /elabftw/tests/_output -cf - coverage.xml coverage \
              | tar -xf -

            mv coverage coverage-html
      - store_artifacts:
          path: coverage-html
          destination: coverage-html
      - codecov/upload

  cypress_e2e_tests:
    parameters:
      browser:
        type: string
    executor: elab-executor
    parallelism: 4
    working_directory: ~/elabftw/elabftw
    shell: /bin/bash --login
    steps:
      - checkout
      - setup_remote_docker:
          version: docker27
      - attach_workspace:
          at: /tmp
      - load_image
      - start_container
      - start_mysql
      - start_cypress
      - copy_cypress_tests
      - populate_db
      - run:
          name: Create folders
          command: mkdir -p cypress/{screenshots,videos}

      - run:
          name: Run Cypress on << parameters.browser >>
          command: |
            SPECS=$(
              find tests/cypress/integration -type f \
                \( -name '*.cy.js' -o -name '*.cy.jsx' -o -name '*.cy.ts' -o -name '*.cy.tsx' \) \
                | sort \
                | circleci tests split --split-by=name \
                | paste -sd, -
            )

            docker exec elab-cypress cypress run \
              --browser << parameters.browser >> \
              --spec "$SPECS" \
              --config baseUrl=https://elabtmp:8080
      - run:
          name: Extract cypress screenshots and videos in case it is enabled again to debug a faulty run
          command: |
            docker cp elab-cypress:/home/node/tests/cypress/screenshots/. cypress/screenshots
            docker cp elab-cypress:/home/node/tests/cypress/videos/. cypress/videos
      - store_artifacts:
          path: cypress
          destination: cypress

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_elabtmp_image
      - code_linters:
          requires:
            - build_elabtmp_image
      - php_unit_tests:
          requires:
            - build_elabtmp_image
      - cypress_e2e_tests:
          requires:
            - build_elabtmp_image
          matrix:
            parameters:
              browser:
                - firefox
                - chrome
                - electron
                - edge
