# CORS headers for REST API endpoints only
%ACAO_HEADER%
%ACAM_HEADER%
%ACAH_HEADER%
%ACAC_HEADER%
%ACEH_HEADER%
more_set_headers 'Access-Control-Allow-Credentials: true';
more_set_headers 'Access-Control-Expose-Headers: Location, Content-Encoding, Content-Disposition, Cache-Control';
