# maintenance mode config file
# when MAINTENANCE_MODE=true
root /elabftw/web/maintenance;
index index.html;
proxy_temp_path /run/proxy;

# Allow only GET requests
if ($request_method != GET) {
    return 405;
}

location = /favicon.ico {
    try_files /favicon.ico =404;
}

location = /maintenance.webp {
    try_files /maintenance.webp =404;
    add_header Cache-Control "public, max-age=3600";
}

# Return index.html for all requests
location / {
    try_files /index.html =404;
}

# explicit error page for 405
error_page 405 /index.html;
