tinymce.addI18n('it_IT',{
"Redo": "Ripeti",
"Undo": "Indietro",
"Cut": "Taglia",
"Copy": "Copia",
"Paste": "Incolla",
"Select all": "Seleziona tutto",
"New document": "Nuovo documento",
"Ok": "Ok",
"Cancel": "Annulla",
"Visual aids": "Aiuti visivi",
"Bold": "Grassetto",
"Italic": "Corsivo",
"Underline": "Sottolineato",
"Strikethrough": "Barrato",
"Superscript": "Apice",
"Subscript": "Pedice",
"Clear formatting": "Cancella la formattazione",
"Align left": "Allinea a sinistra",
"Align center": "Allinea al centro",
"Align right": "Allinea a destra",
"Justify": "Giustifica",
"Bullet list": "Elenchi puntati",
"Numbered list": "Elenchi numerati",
"Decrease indent": "Riduci indentazione",
"Increase indent": "Aumenta indentazione",
"Close": "Chiudi",
"Formats": "Formati",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Il tuo browser non supporta l'accesso diretto negli Appunti. Per favore usa i tasti di scelta rapida Ctrl+X\/C\/V.",
"Headers": "Intestazioni",
"Header 1": "Intestazione 1",
"Header 2": "Intestazione 2",
"Header 3": "Intestazione 3",
"Header 4": "Intestazione 4",
"Header 5": "Intestazione 5",
"Header 6": "Intestazione 6",
"Headings": "Intestazioni",
"Heading 1": "Intestazione 1",
"Heading 2": "Intestazione 2",
"Heading 3": "Intestazione 3",
"Heading 4": "Intestazione 4",
"Heading 5": "Intestazione 5",
"Heading 6": "Intestazione 6",
"Preformatted": "Preformattato",
"Div": "Div",
"Pre": "Pre",
"Code": "Codice",
"Paragraph": "Paragrafo",
"Blockquote": "Blockquote",
"Inline": "Stili",
"Blocks": "Blocchi",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Incolla \u00e8 in modalit\u00e0 testo normale. I contenuti sono incollati come testo normale se non disattivi l'opzione.",
"Fonts": "Caratteri",
"Font Sizes": "Dimensioni caratteri",
"Class": "Classe",
"Browse for an image": "Scegli un'immagine",
"OR": "O",
"Drop an image here": "Rilascia una immagine qui",
"Upload": "Carica",
"Block": "Blocco",
"Align": "Allinea",
"Default": "Predefinito",
"Circle": "Cerchio",
"Disc": "Disco",
"Square": "Quadrato",
"Lower Alpha": "Lettere minuscole",
"Lower Greek": "Lettere greche minuscole",
"Lower Roman": "Numeri romani minuscoli",
"Upper Alpha": "Lettere maiuscole",
"Upper Roman": "Numeri romani maiuscoli",
"Anchor...": "Ancora...",
"Name": "Nome",
"Id": "Id",
"Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "L'id dovrebbe cominciare con una lettera, seguito solo da lettere, numeri, linee, punti, virgole o sottolineati.",
"You have unsaved changes are you sure you want to navigate away?": "Non hai salvato le modifiche, sei sicuro di andartene?",
"Restore last draft": "Ripristina l'ultima bozza",
"Special characters...": "Caratteri speciali...",
"Source code": "Codice Sorgente",
"Insert\/Edit code sample": "Inserisci\/Modifica esempio di codice",
"Language": "Lingua",
"Code sample...": "Esempio di codice...",
"Color Picker": "Selettore del colore",
"R": "R",
"G": "G",
"B": "B",
"Left to right": "Da sinistra a destra",
"Right to left": "Da destra a sinistra",
"Emoticons...": "Emoticons...",
"Metadata and Document Properties": "Metadata e propriet\u00e0 del documento",
"Title": "Titolo",
"Keywords": "Keywords",
"Description": "Description",
"Robots": "Robot",
"Author": "Autore",
"Encoding": "Codifica",
"Fullscreen": "Schermo intero",
"Action": "Azione",
"Shortcut": "Scorciatoia",
"Help": "Aiuto",
"Address": "Indirizzo",
"Focus to menubar": "Focus sulla barra del menu",
"Focus to toolbar": "Focus sulla barra degli strumenti",
"Focus to element path": "Focus sul percorso dell'elemento",
"Focus to contextual toolbar": "Focus sulla barra degli strumenti contestuale",
"Insert link (if link plugin activated)": "Inserisci un collegamento (se il plugin link \u00e8 attivato)",
"Save (if save plugin activated)": "Salva (se il plugin salva \u00e8 attivato)",
"Find (if searchreplace plugin activated)": "Trova (se il plugin trova e sostituisci \u00e8 attivato)",
"Plugins installed ({0}):": "Plugin installati ({0}):",
"Premium plugins:": "Plugin Premium:",
"Learn more...": "Per saperne di pi\u00f9...",
"You are using {0}": "Stai usando {0}",
"Plugins": "Plugin",
"Handy Shortcuts": "Scorciatoia pratica",
"Horizontal line": "Linea orizzontale",
"Insert\/edit image": "Aggiungi\/Modifica Immagine",
"Image description": "Descrizione immagine",
"Source": "Sorgente",
"Dimensions": "Dimensioni",
"Constrain proportions": "Mantieni proporzioni",
"General": "Generale",
"Advanced": "Avanzato",
"Style": "Stile",
"Vertical space": "Spazio verticale",
"Horizontal space": "Spazio orizzontale",
"Border": "Bordo",
"Insert image": "Inserisci immagine",
"Image...": "Immagine...",
"Image list": "Elenco immagini",
"Rotate counterclockwise": "Ruota in senso antiorario",
"Rotate clockwise": "Ruota in senso orario",
"Flip vertically": "Rifletti verticalmente",
"Flip horizontally": "Rifletti orizzontalmente",
"Edit image": "Modifica immagine",
"Image options": "Opzioni immagine",
"Zoom in": "Ingrandisci",
"Zoom out": "Rimpicciolisci",
"Crop": "Taglia",
"Resize": "Ridimensiona",
"Orientation": "Orientamento",
"Brightness": "Luminosit\u00e0",
"Sharpen": "Contrasta",
"Contrast": "Contrasto",
"Color levels": "Livelli di colore",
"Gamma": "Gamma",
"Invert": "Inverti",
"Apply": "Applica",
"Back": "Indietro",
"Insert date\/time": "Inserisci Data\/Ora",
"Date\/time": "Data\/Ora",
"Insert\/Edit Link": "Inserisci\/Modifica collegamento",
"Insert\/edit link": "Inserisci\/Modifica collegamento",
"Text to display": "Testo da visualizzare",
"Url": "Url",
"Open link in...": "Apri collegamento in...",
"Current window": "Attuale finestra",
"None": "Nessuno",
"New window": "Nuova finestra",
"Remove link": "Rimuovi collegamento",
"Anchors": "Ancora",
"Link...": "Collegamento...",
"Paste or type a link": "Incolla o digita un collegamento",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "L'URL inserito sembra essere un indirizzo email. Vuoi aggiungere il prefisso necessario mailto:?",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "L'URL inserito sembra essere un collegamento esterno. Vuoi aggiungere il prefisso necessario http:\/\/?",
"Link list": "Elenco collegamenti",
"Insert video": "Inserisci Video",
"Insert\/edit video": "Inserisci\/Modifica Video",
"Insert\/edit media": "Inserisci\/Modifica Media",
"Alternative source": "Sorgente alternativa",
"Alternative source URL": "URL sorgente alternativa",
"Media poster (Image URL)": "Poster dell'oggetto multimediale (URL dell'immagine)",
"Paste your embed code below:": " Incolla il codice d'incorporamento di seguito: ",
"Embed": "Incorpora",
"Media...": "Media...",
"Nonbreaking space": "spazio indivisibile",
"Page break": "Interruzione di pagina",
"Paste as text": "Incolla senza formattazioni",
"Preview": "Anteprima",
"Print...": "Stampa...",
"Save": "Salva",
"Find": "Trova",
"Replace with": "Sostituisci con",
"Replace": "Sostituisci",
"Replace all": "Sostituisci tutto",
"Previous": "Precedente",
"Next": "Successivo",
"Find and replace...": "Trova e sostituisci...",
"Could not find the specified string.": "Impossibile trovare il testo specificato.",
"Match case": "Maiuscole\/Minuscole esatte",
"Find whole words only": "Trova solo parole intere",
"Spell check": "Controlla ortografia",
"Ignore": "Ignora",
"Ignore all": "Ignora tutto",
"Finish": "Termina",
"Add to Dictionary": "Aggiungi al dizionario",
"Insert table": "Inserisci tabella",
"Table properties": "Proprie\u00e0 della tabella",
"Delete table": "Cancella tabella",
"Cell": "Cella",
"Row": "Riga",
"Column": "Colonna",
"Cell properties": "Propriet\u00e0 della cella",
"Merge cells": "Unisci le celle",
"Split cell": "Dividi la cella",
"Insert row before": "Inserisci riga prima",
"Insert row after": "Inserisci riga dopo",
"Delete row": "Cancella riga",
"Row properties": "Propriet\u00e0 della riga",
"Cut row": "Taglia riga",
"Copy row": "Copia riga",
"Paste row before": "Incolla riga prima",
"Paste row after": "Incolla riga dopo",
"Insert column before": "Inserisci colonna prima",
"Insert column after": "Inserisci colonna dopo",
"Delete column": "Cancella colonna",
"Cols": "Colonne",
"Rows": "Righe",
"Width": "Larghezza",
"Height": "Altezza",
"Cell spacing": "Spacing della cella",
"Cell padding": "Padding della cella",
"Show caption": "Mostra didascalia",
"Left": "a sinistra",
"Center": "al centro",
"Right": "a destra",
"Cell type": "Tipo di cella",
"Scope": "Ambito",
"Alignment": "Allineamento",
"H Align": "Allineamento orizzontale",
"V Align": "Allineamento verticale",
"Top": "In alto",
"Middle": "In mezzo",
"Bottom": "In basso",
"Header cell": "Cella d'intestazione",
"Row group": "Gruppo di righe",
"Column group": "Gruppo di colonne",
"Row type": " Tipo di riga",
"Header": "Intestazione",
"Body": "Corpo",
"Footer": "Pi\u00e8 di pagina",
"Border color": "Colore del bordo",
"Insert template...": "Inserisci modello...",
"Templates": "Modello",
"Template": "Modello",
"Text color": "Colore del testo",
"Background color": "Colore di sfondo",
"Custom...": "Personalizza...",
"Custom color": "Colore personalizzato",
"No color": "Nessun colore",
"Remove color": "Rimuovi il colore",
"Table of Contents": "Tabella dei contenuti",
"Show blocks": "Mostra blocchi",
"Show invisible characters": "Mostra caratteri invisibili",
"Word count": "Conta le parole",
"Words: {0}": "Parole: {0}",
"{0} words": "{0} parole ",
"File": "File",
"Edit": "Modifica",
"Insert": "Inserisci",
"View": "Visualizza",
"Format": "Formato",
"Table": "Tabella",
"Tools": "Strumenti",
"Powered by {0}": "Fornito da {0}",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Area Rich Text. Premi ALT-F9 per il men\u00f9. Premi ALT-F10 per la barra degli strumenti. Premi ALT-0 per l'aiuto.",
"Image title": " Titolo immagine",
"Border width": " Larghezza bordo",
"Border style": " Stile del bordo",
"Error": "Errore",
"Warn": "Avviso",
"Valid": "Valido",
"To open the popup, press Shift+Enter": "Per aprire il popup, premi Shift+Enter",
"Rich Text Area. Press ALT-0 for help.": "Area Rich Text. Premi ALT-0 per l'aiuto.",
"System Font": "Carattere di sistema",
"Failed to upload image: {0}": "Caricamento immagine fallito: {0}",
"Failed to load plugin: {0} from url {1}": "Caricamento plugin fallito: {0} dall'url {1}",
"Failed to load plugin url: {0}": "Caricamento plugin fallito url: {0}",
"Failed to initialize plugin: {0}": "Inizializzazione plugin fallita: {0}",
"example": "Esempio",
"Search": "Cerca",
"All": "Tutti",
"Currency": "Valuta",
"Text": "Testo",
"Quotations": "Virgolette\/Apici",
"Mathematical": "Matematica",
"Extended Latin": "Latino esteso",
"Symbols": "Simboli",
"Arrows": "Frecce",
"User Defined": "Definito dall'utente",
"dollar sign": "Simbolo del dollaro",
"currency sign": "Simbolo di valuta",
"euro-currency sign": "Simbolo dell'euro",
"colon sign": "Simbolo del col\u00f3n",
"cruzeiro sign": "Simbolo del cruzeiro",
"french franc sign": "Simbolo del franco francese",
"lira sign": "Simbolo della lira",
"mill sign": "Simbolo del mill",
"naira sign": "Simbolo della naira",
"peseta sign": "Simbolo della peseta",
"rupee sign": "Simbolo della rup\u00eca",
"won sign": "Simbolo del won",
"new sheqel sign": "Simbolo del nuovo shekel",
"dong sign": "Simbolo del dong",
"kip sign": "Simbolo del kip",
"tugrik sign": "Simbolo del tugrik",
"drachma sign": "Simbolo della dracma",
"german penny symbol": "Simbolo del pfennig tedesco",
"peso sign": "Simbolo del peso",
"guarani sign": "Simbolo del guaran\u00ec",
"austral sign": "Simbolo dell'austral",
"hryvnia sign": "Simbolo della hryvnia",
"cedi sign": "Simbolo del cedi",
"livre tournois sign": "Simbolo della lira di Tours",
"spesmilo sign": "Simbolo dello spesmilo",
"tenge sign": "Simbolo del tenge",
"indian rupee sign": "Simbolo della rup\u00eca indiana",
"turkish lira sign": "Simbolo della lira turca",
"nordic mark sign": "Simbolo del marco nordico",
"manat sign": "Simbolo del manat",
"ruble sign": "Simbolo del rublo",
"yen character": "Simbolo dello yen",
"yuan character": "Simbolo dello yuan",
"yuan character, in hong kong and taiwan": "Simbolo dello yuan, in hong kong e taiwan",
"yen\/yuan character variant one": "Simbolo yen\/yuan variante uno",
"Loading emoticons...": " Caricamento emoticon...",
"Could not load emoticons": " Impossibile caricare le emoticon",
"People": "Persone",
"Animals and Nature": "Animali e Natura",
"Food and Drink": "Cibi e bevande",
"Activity": "Attivit\u00e0",
"Travel and Places": "Viaggi e Luoghi",
"Objects": "Oggetti",
"Flags": "Bandiere",
"Characters": "Caratteri",
"Characters (no spaces)": "Caratteri (senza spazi)",
"Error: Form submit field collision.": "Errore: conflitto di campi nel modulo inviato.",
"Error: No form element found.": " Errore: Nessun elemento del form trovato",
"Update": "Aggiorna",
"Color swatch": " Campione di colore",
"Turquoise": "Turchese",
"Green": "Verde",
"Blue": "Blu",
"Purple": "Viola",
"Navy Blue": "Blu Navy",
"Dark Turquoise": "Turchese scuro",
"Dark Green": "Verde scurp",
"Medium Blue": "Blu medio",
"Medium Purple": "Viola medio",
"Midnight Blue": "Blu notte",
"Yellow": "Giallo",
"Orange": "Arancione",
"Red": "Rosso",
"Light Gray": "Grigio chiaro",
"Gray": "Grigio",
"Dark Yellow": "Giallo scuro",
"Dark Orange": "Arancione scuro",
"Dark Red": "Rosso scuro",
"Medium Gray": " Grigio medio",
"Dark Gray": " Grigio scuro",
"Black": " Nero ",
"White": "Bianco",
"Switch to or from fullscreen mode": "Attiva\/disattiva la modalit\u00e0 schermo intero",
"Open help dialog": "Apri la finestra di aiuto",
"history": "Cronologia",
"styles": "Stili",
"formatting": "Formattazione",
"alignment": "Allineamento",
"indentation": "Indentazione",
"permanent pen": "penna indelebile",
"comments": "Commenti"
});