networks:
  default:
    name: elabftw-net
services:
  web:
    image: elabftw/circleci
    # circleci runs as id 1001 and gid 1002
    user: 1001:1002
    build:
      context: ../..
      dockerfile: ./containers/circleci/Dockerfile
    container_name: elabtmp
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - FOWNER
      - DAC_OVERRIDE
    environment:
      - DB_HOST=mysqltmp
      - DB_NAME=phpunit
      - DB_USER=phpunit
      # oMg tHe sOuRcE CoDe cOnTaInS PaSsWoRdS In pLaIn tExT!!!
      - DB_PASSWORD=phpunit
      - SECRET_KEY=def00000195a92432f2ebb86bf6e9b9646b45ea955cab7b8f2d96ba2259a85c9e09b04647078c425c5392cb631fa3d9816974bbe8e458d61e16f897ef36c0def362458fd
      - SERVER_NAME=elabtmp
      - DISABLE_HTTPS=false
      - ENABLE_LETSENCRYPT=false
      - MAX_UPLOAD_SIZE=200M
      - PHP_TIMEZONE=Europe/Paris
      - TZ=Europe/Paris
      - DEV_MODE=true
      - SITE_URL=https://elabtmp:8080
      - ELAB_AWS_ACCESS_KEY=yep
      - ELAB_AWS_SECRET_KEY=yop
      - MAX_PHP_MEMORY=512M
    healthcheck:
      test: /etc/nginx/healthcheck.sh
      interval: 10s
      timeout: 5s
      retries: 3
    tmpfs:
      - /run/nginx:mode=1770,uid=1001,gid=1002
      - /run/php:mode=1770,uid=1001,gid=1002
      - /run/elabftw/cache:mode=1770,uid=1001,gid=1002,exec,nosuid,nodev
      - /elabftw/tests/_output:mode=1770,uid=1001,gid=1002
      - /elabftw/tests/_support/_generated:mode=1770,uid=1001,gid=1002
      - /var/cache/nginx:mode=755,uid=1001,gid=1002,noexec,nosuid,nodev
      - /var/lib/elabftw/exports:mode=755,uid=1001,gid=1002,noexec,nosuid,nodev
      - /var/lib/elabftw/uploads:mode=755,uid=1001,gid=1002,noexec,nosuid,nodev
