-- schema 166
CREATE TABLE IF NOT EXISTS fingerprints (
  `id` int unsigned not null auto_increment,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `item_id` int unsigned not null,
  fp0  INT unsigned NOT NULL,
  fp1  INT unsigned NOT NULL,
  fp2  INT unsigned NOT NULL,
  fp3  INT unsigned NOT NULL,
  fp4  INT unsigned NOT NULL,
  fp5  INT unsigned NOT NULL,
  fp6  INT unsigned NOT NULL,
  fp7  INT unsigned NOT NULL,
  fp8  INT unsigned NOT NULL,
  fp9  INT unsigned NOT NULL,
  fp10 INT unsigned NOT NULL,
  fp11 INT unsigned NOT NULL,
  fp12 INT unsigned NOT NULL,
  fp13 INT unsigned NOT NULL,
  fp14 INT unsigned NOT NULL,
  fp15 INT unsigned NOT NULL,
  fp16 INT unsigned NOT NULL,
  fp17 INT unsigned NOT NULL,
  fp18 INT unsigned NOT NULL,
  fp19 INT unsigned NOT NULL,
  fp20 INT unsigned NOT NULL,
  fp21 INT unsigned NOT NULL,
  fp22 INT unsigned NOT NULL,
  fp23 INT unsigned NOT NULL,
  fp24 INT unsigned NOT NULL,
  fp25 INT unsigned NOT NULL,
  fp26 INT unsigned NOT NULL,
  fp27 INT unsigned NOT NULL,
  fp28 INT unsigned NOT NULL,
  fp29 INT unsigned NOT NULL,
  fp30 INT unsigned NOT NULL,
  fp31 INT unsigned NOT NULL,
  primary key(`id`)
);

UPDATE config SET conf_value = 166 WHERE conf_name = 'schema';
