-- schema 167
CREATE TABLE IF NOT EXISTS fingerprints (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `item_id` INT UNSIGNED NOT NULL,
  fp0  INT UNSIGNED NOT NULL,
  fp1  INT UNSIGNED NOT NULL,
  fp2  INT UNSIGNED NOT NULL,
  fp3  INT UNSIGNED NOT NULL,
  fp4  INT UNSIGNED NOT NULL,
  fp5  INT UNSIGNED NOT NULL,
  fp6  INT UNSIGNED NOT NULL,
  fp7  INT UNSIGNED NOT NULL,
  fp8  INT UNSIGNED NOT NULL,
  fp9  INT UNSIGNED NOT NULL,
  fp10 INT UNSIGNED NOT NULL,
  fp11 INT UNSIGNED NOT NULL,
  fp12 INT UNSIGNED NOT NULL,
  fp13 INT UNSIGNED NOT NULL,
  fp14 INT UNSIGNED NOT NULL,
  fp15 INT UNSIGNED NOT NULL,
  fp16 INT UNSIGNED NOT NULL,
  fp17 INT UNSIGNED NOT NULL,
  fp18 INT UNSIGNED NOT NULL,
  fp19 INT UNSIGNED NOT NULL,
  fp20 INT UNSIGNED NOT NULL,
  fp21 INT UNSIGNED NOT NULL,
  fp22 INT UNSIGNED NOT NULL,
  fp23 INT UNSIGNED NOT NULL,
  fp24 INT UNSIGNED NOT NULL,
  fp25 INT UNSIGNED NOT NULL,
  fp26 INT UNSIGNED NOT NULL,
  fp27 INT UNSIGNED NOT NULL,
  fp28 INT UNSIGNED NOT NULL,
  fp29 INT UNSIGNED NOT NULL,
  fp30 INT UNSIGNED NOT NULL,
  fp31 INT UNSIGNED NOT NULL,
  primary key(`id`)
);
CREATE TABLE storage_units (
    id INT unsigned NOT NULL AUTO_INCREMENT,
    level_name VARCHAR(255),  -- Describes the level, e.g., Building, Room
    unit_name VARCHAR(255),   -- Describes the name of the specific unit, e.g., Building A, Room 101
    parent_id INT unsigned,            -- Refers to the parent storage unit
    FOREIGN KEY (parent_id) REFERENCES storage_units(id) ON DELETE CASCADE,
    PRIMARY KEY(`id`)
);

UPDATE config SET conf_value = 167 WHERE conf_name = 'schema';
