-- Schema 45
START TRANSACTION;
    ALTER TABLE `experiments_templates` ADD CONSTRAINT `fk_experiments_templates_teams_id` FOREIGN KEY (`team`) REFERENCES `teams`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `experiments` ADD CONSTRAINT `fk_experiments_teams_id` FOREIGN KEY (`team`) REFERENCES `teams`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `experiments` ADD CONSTRAINT `fk_experiments_users_userid` FOREIGN KEY (`userid`) REFERENCES `users`(`userid`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `experiments_comments` ADD CONSTRAINT `fk_experiments_comments_experiments_id` FOREIGN KEY (`item_id`) REFERENCES `experiments`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `experiments_comments` ADD CONSTRAINT `fk_experiments_comments_users_userid` FOREIGN KEY (`userid`) REFERENCES `users`(`userid`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `experiments_links` ADD CONSTRAINT `fk_experiments_links_experiments_id` FOREIGN KEY (`item_id`) REFERENCES `experiments`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `experiments_links` ADD CONSTRAINT `fk_experiments_links_items_id` FOREIGN KEY (`link_id`) REFERENCES `items`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `experiments_revisions` ADD CONSTRAINT `fk_experiments_revisions_experiments_id` FOREIGN KEY (`item_id`) REFERENCES `experiments`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `experiments_revisions` ADD CONSTRAINT `fk_experiments_revisions_users_userid` FOREIGN KEY (`userid`) REFERENCES `users`(`userid`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `items_revisions` ADD CONSTRAINT `fk_items_revisions_items_id` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `items_revisions` ADD CONSTRAINT `fk_items_revisions_users_userid` FOREIGN KEY (`userid`) REFERENCES `users`(`userid`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `experiments_steps` ADD CONSTRAINT `fk_experiments_steps_experiments_id` FOREIGN KEY (`item_id`) REFERENCES `experiments`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `items` ADD CONSTRAINT `fk_items_teams_id` FOREIGN KEY (`team`) REFERENCES `teams`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `items_comments` ADD CONSTRAINT `fk_items_comments_items_id` FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `items_comments` ADD CONSTRAINT `fk_items_comments_users_userid` FOREIGN KEY (`userid`) REFERENCES `users`(`userid`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `items_types` ADD CONSTRAINT `fk_items_types_teams_id` FOREIGN KEY (`team`) REFERENCES `teams`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `status` ADD CONSTRAINT `fk_status_teams_id` FOREIGN KEY (`team`) REFERENCES `teams`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `tags` ADD CONSTRAINT `fk_tags_teams_id` FOREIGN KEY (`team`) REFERENCES `teams`(`id`) ON DELETE cascade ON UPDATE cascade;
    -- ALTER TABLE `tags2entity` ADD CONSTRAINT `fk_tags2entity_tags_id` FOREIGN KEY (`tag_id`) REFERENCES `tags`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `team_events` ADD CONSTRAINT `fk_team_events_teams_id` FOREIGN KEY (`team`) REFERENCES `teams`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `team_events` ADD CONSTRAINT `fk_team_events_users_userid` FOREIGN KEY (`userid`) REFERENCES `users`(`userid`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `team_groups` ADD CONSTRAINT `fk_team_groups_teams_id` FOREIGN KEY (`team`) REFERENCES `teams`(`id`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `todolist` ADD CONSTRAINT `fk_todolist_users_userid` FOREIGN KEY (`userid`) REFERENCES `users`(`userid`) ON DELETE cascade ON UPDATE cascade;
    ALTER TABLE `users` ADD CONSTRAINT `fk_users_teams_id` FOREIGN KEY (`team`) REFERENCES `teams`(`id`) ON DELETE cascade ON UPDATE cascade;
    -- ALTER TABLE `users2team_groups` ADD CONSTRAINT `fk_users2team_groups_users_userid` FOREIGN KEY (`userid`) REFERENCES `users`(`userid`) ON DELETE cascade ON UPDATE cascade;
    -- ALTER TABLE `users2team_groups` ADD CONSTRAINT `fk_users2team_groups_team_groups_id` FOREIGN KEY (`groupid`) REFERENCES `team_groups`(`id`) ON DELETE cascade ON UPDATE cascade;
    UPDATE config SET conf_value = 45 WHERE conf_name = 'schema';
COMMIT;
