-- schema 175
ALTER TABLE `team_events` ADD `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `team_events` ADD `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `users` ADD `scope_events` TINYINT UNSIGNED NOT NULL DEFAULT 2 AFTER `scope_items`;
