-- schema 175
ALTER TABLE `compounds` ADD COLUMN `is_antibiotic` TINYINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `compounds` ADD COLUMN `is_drug` TINYINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `compounds` ADD COLUMN `is_ed2health` TINYINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `compounds` ADD COLUMN `is_ed2env` TINYINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `compounds` ADD COLUMN `is_pbt` TINYINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `compounds` ADD COLUMN `is_pmt` TINYINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `compounds` ADD COLUMN `is_vpvb` TINYINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `compounds` ADD COLUMN `is_vpvm` TINYINT UNSIGNED NOT NULL DEFAULT 0;
