-- revert schema 170
ALTER TABLE compounds
DROP COLUMN `is_corrosive` TINYINT UNSIGNED NOT NULL DEFAULT 0,
DROP COLUMN `is_explosive` TINYINT UNSIGNED NOT NULL DEFAULT 0,
DROP COLUMN `is_flammable` TINYINT UNSIGNED NOT NULL DEFAULT 0,
DROP COLUMN `is_gas_under_pressure` TINYINT UNSIGNED NOT NULL DEFAULT 0,
DROP COLUMN `is_hazardous2env` TINYINT UNSIGNED NOT NULL DEFAULT 0,
DROP COLUMN `is_hazardous2health` TINYINT UNSIGNED NOT NULL DEFAULT 0,
DROP COLUMN `is_oxidising` TINYINT UNSIGNED NOT NULL DEFAULT 0,
DROP COLUMN `is_toxic` TINYINT UNSIGNED NOT NULL DEFAULT 0;
UPDATE config SET conf_value = 169 WHERE conf_name = 'schema';
