-- revert schema 167
DROP TABLE IF EXISTS compounds_fingerprints;
DROP TABLE IF EXISTS compounds;
DROP TABLE IF EXISTS compounds2experiments;
DROP TABLE IF EXISTS compounds2experiments_templates;
DROP TABLE IF EXISTS compounds2items;
DROP TABLE IF EXISTS compounds2items_types;
ALTER TABLE `experiments` DROP FOREIGN KEY `fk_experiments_storage`;
ALTER TABLE experiments DROP COLUMN storage;
ALTER TABLE experiments DROP COLUMN qty_stored;
ALTER TABLE experiments DROP COLUMN qty_unit;
ALTER TABLE `experiments_templates` DROP FOREIGN KEY `fk_experiments_templates_storage`;
ALTER TABLE experiments_templates DROP COLUMN storage;
ALTER TABLE experiments_templates DROP COLUMN qty_stored;
ALTER TABLE experiments_templates DROP COLUMN qty_unit;
ALTER TABLE `items` DROP FOREIGN KEY `fk_items_storage`;
ALTER TABLE items DROP COLUMN storage;
ALTER TABLE items DROP COLUMN qty_stored;
ALTER TABLE items DROP COLUMN qty_unit;
ALTER TABLE `items_types` DROP FOREIGN KEY `fk_items_types_storage`;
ALTER TABLE items_types DROP COLUMN storage;
ALTER TABLE items_types DROP COLUMN qty_stored;
ALTER TABLE items_types DROP COLUMN qty_unit;
DROP TABLE IF EXISTS storage_units;
ALTER TABLE `tags` DROP INDEX `unique_tags_team_tag`;
UPDATE config SET conf_value = 166 WHERE conf_name = 'schema';
