-- schema 196
ALTER TABLE `experiments` ADD COLUMN `hide_main_text` TINYINT UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `items` ADD COLUMN `hide_main_text` TINYINT UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `experiments_templates` ADD COLUMN `hide_main_text` TINYINT UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `items_types` ADD COLUMN `hide_main_text` TINYINT UNSIGNED NULL DEFAULT NULL;
