-- schema 205
ALTER TABLE `experiments`
  ADD COLUMN `created_from_id` INT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `created_from_type` TINYINT UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `items`
  ADD COLUMN `created_from_id` INT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `created_from_type` TINYINT UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `experiments_templates`
  ADD COLUMN `created_from_id` INT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `created_from_type` TINYINT UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `items_types`
  ADD COLUMN `created_from_id` INT UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN `created_from_type` TINYINT UNSIGNED NULL DEFAULT NULL;
