<?php

/**
 * @package   Elabftw\Elabftw
 * @author    Nicolas CARPi <nico-git@deltablot.email>
 * @copyright 2012 Nicolas CARPi
 * @license   https://www.gnu.org/licenses/agpl-3.0.html AGPL-3.0
 * @see       https://www.elabftw.net Official website
 */

declare(strict_types=1);

namespace Elabftw\Exceptions;

use Elabftw\Enums\Messages;
use Exception;
use Psr\Log\LoggerInterface;

/**
 * Errors generated by eLabFTW App itself
 */
class AppException extends Exception
{
    protected Messages $error = Messages::GenericError;

    public function __construct(?string $message = null, ?int $code = null, ?Exception $previous = null, private ?string $description = null)
    {
        $message ??= $this->getErrorMessage();
        $code ??= $this->getHttpCode();
        parent::__construct($message, $code, $previous);
    }

    public function getDescription(): string
    {
        return $this->description ?? '';
    }

    public function getHttpCode(): int
    {
        return $this->error->toHttpCode();
    }

    public function emitLog(LoggerInterface $logger, int $userid): void
    {
        $logger->log(
            $this->getHttpCode() >= 500 ? 'error' : 'notice',
            $this->getMessage(),
            array(
                'userid' => $userid,
                'request-id' => $_SERVER['ELABFTW_REQUEST_ID'] ?? '',
                'exception' => $this,
            ),
        );
    }

    protected function getErrorMessage(): string
    {
        return $this->error->toHuman();
    }
}
