<?php

/**
 * @package   Elabftw\Elabftw
 * @author    Nicolas CARPi <nico-git@deltablot.email>
 * @copyright 2012 Nicolas CARPi
 * @license   https://www.gnu.org/licenses/agpl-3.0.html AGPL-3.0
 * @see       https://www.elabftw.net Official website
 */

declare(strict_types=1);

namespace Elabftw\Exceptions;

use Elabftw\Elabftw\App;
use Elabftw\Enums\Messages;
use Exception;
use Psr\Log\LoggerInterface;
use Symfony\Component\HttpFoundation\Response;

/**
 * Errors generated by eLabFTW App itself
 */
class AppException extends Exception
{
    protected Messages $error = Messages::GenericError;

    public function __construct(?string $message = null, ?int $code = null, ?Exception $previous = null, private ?string $description = null)
    {
        $message ??= $this->getErrorMessage();
        $code ??= $this->getHttpCode();
        parent::__construct($message, $code, $previous);
    }

    public function getDescription(): string
    {
        return $this->description ?? '';
    }

    public function getResponseFromException(App $app): Response
    {
        $this->emitLog($app->Log, $app->Session->get('userid') ?? -1);
        $template = 'error.html';
        $renderArr = array('error' => $this->getMessage());
        $Response = new Response();
        $Response->setContent($app->render($template, $renderArr));
        // use explicit toHttpCode here as we could have a code that is different from an http one
        $Response->setStatusCode($this->error->toHttpCode());
        return $Response;
    }

    public function getHttpCode(): int
    {
        return $this->error->toHttpCode();
    }

    protected function getErrorMessage(): string
    {
        return $this->error->toHuman();
    }

    // the default is to not emit log, and some exceptions can override this to log something
    protected function emitLog(LoggerInterface $logger, int $userid): void {}
}
