import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
   installSidebar: [{ type: "autogenerated", dirName: "install" }],
   usageSidebar: [{ type: "autogenerated", dirName: "usage" }],
   tutorialsSidebar: [{ type: "autogenerated", dirName: "tutorials" }],
   contributingSidebar: [{ type: "autogenerated", dirName: "contributing" }],
};

export default sidebars;
