name: Build nightly elabimg

on:
  schedule:
    - cron: "42 01 * * *"

## GITHUB_TOKEN authentication
permissions:
  contents: write
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  buildandpush:
    runs-on: ubuntu-latest
    name: Build images and push to Docker Hub
    steps:
      # https://github.com/CycodeLabs/cimon-action
      - name: Cimon supply chain attack protection
        uses: cycodelabs/cimon-action@f99ad5557cb80964bc2b2e76a47bf4b5ba6e323b # v0.10
        with:
          prevent: true
          allowed-hosts: >
            auth.docker.io
            codeload.github.com
            get.trivy.dev
            check.trivy.dev
            dl-cdn.alpinelinux.org
            docker.io
            ghcr.io
            index.docker.io
            mirror.gcr.io
            nginx.org
            packagist.org
            pkg-containers.githubusercontent.com
            production.cloudflare.docker.com
            raw.githubusercontent.com
            registry.yarnpkg.com
            registry-1.docker.io
            repo.yarnpkg.com
            registry.npmjs.org
            *.sigstore.dev
            hooks.deltablot.dev

      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # https://github.com/docker/build-push-action#multi-platform-image
      - name: Build nightly and push to docker
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        id: push
        with:
          context: .
          file: containers/elabimg/Dockerfile
          # the scope parameter is necessary when doing multi arch builds or we'll always miss cache
          cache-from: type=gha,scope=${{ matrix.os }}-${{ matrix.arch }}
          cache-to:   type=gha,mode=max,scope=${{ matrix.os }}-${{ matrix.arch }}
          platforms: linux/arm64,linux/amd64
          sbom: true
          push: true
          build-args: |
              ELABFTW_VERSION=${{ github.ref_name }}
          tags: |
              elabftw/elabimg:nightly


      # TRIVY scans disabled because of https://socket.dev/blog/trivy-under-attack-again-github-actions-compromise
      # VULN SCAN
      #- name: Run Trivy vulnerability scanner
      #  uses: aquasecurity/trivy-action@master
      #  with:
      #    image-ref: elabftw/elabimg:nightly
      #    format: 'table'
      #    exit-code: '1'
      #    ignore-unfixed: true
      #    vuln-type: 'os,library'
      #    # use only the vuln scanner to avoid OOM kill with secrets scanning
      #    #not working: scanners: 'vuln'
      #    severity: 'CRITICAL,HIGH'

      # SBOM
      #- name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
      #  uses: aquasecurity/trivy-action@master
      #  with:
      #    scan-type: 'fs'
      #    format: 'github'
      #    output: 'dependency-results.sbom.json'
      #    scan-ref: '.'
      #    github-pat: ${{ secrets.GITHUB_TOKEN }}

      # ATTESTATION
      - name: Create build provenance attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-name: docker.io/elabftw/elabimg
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
