name: Build and push elabtmp image

on:
  push:

## GITHUB_TOKEN authentication
permissions:
  contents: write

jobs:
    build_elabtmp:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout elabftw repo
              uses: actions/checkout@v3
              with:
                ref: ${{ github.ref_name }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # https://github.com/docker/login-action#docker-hub
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}

            # https://github.com/docker/build-push-action#multi-platform-image
            # https://docs.docker.com/build/ci/github-actions/cache/
            - name: Build elabtmp and push to Docker Hub
              uses: docker/build-push-action@v4
              with:
                context: .
                file: tests/elabtmp.Dockerfile
                platforms: linux/amd64
                push: true
                cache-from: type=gha
                cache-to: type=gha,mode=max
                tags: |
                  elabftw/elabtmp:latest
