name: Build and push the chem plugin image

# Triggered by change in the corresponding folder
on:
  push:
    paths:
      - 'containers/chem-plugin/**'
  pull_request:
    paths:
      - 'containers/chem-plugin/**'

## GITHUB_TOKEN authentication
permissions:
  contents: read

jobs:
    buildandpush:
        runs-on: ubuntu-latest
        steps:
            # https://github.com/CycodeLabs/cimon-action
            - name: Cimon supply chain attack protection
              uses: cycodelabs/cimon-action@v0
              with:
                prevent: true
                allowed-hosts: >
                  auth.docker.io
                  codeload.github.com
                  dl-cdn.alpinelinux.org
                  docker.io
                  ghcr.io
                  index.docker.io
                  mirror.gcr.io
                  nginx.org
                  packagist.org
                  pkg-containers.githubusercontent.com
                  production.cloudflare.docker.com
                  raw.githubusercontent.com
                  registry.yarnpkg.com
                  repo.yarnpkg.com
                  registry.npmjs.org
                  hooks.deltablot.dev

            - name: Checkout repo
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                ref: ${{ github.ref_name }}

            # https://github.com/marketplace/actions/docker-setup-buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

            # https://github.com/docker/login-action#docker-hub
            - name: Login to Docker Hub
              uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}

            # https://github.com/docker/build-push-action#multi-platform-image
            # https://docs.docker.com/build/ci/github-actions/cache/
            - name: Build latest release for all platforms and push to Docker Hub
              uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
              with:
                context: .
                file: containers/chem-plugin/Dockerfile
                platforms: linux/amd64
                push: true
                # the scope parameter is necessary when doing multi arch builds or we'll always miss cache
                cache-from: type=gha,scope=${{ runner.os }}-${{ runner.arch }}
                cache-to:   type=gha,mode=max,scope=${{ runner.os }}-${{ runner.arch }}
                sbom: true
                tags: |
                    elabftw/chem-plugin:stable
                    elabftw/chem-plugin:latest
                    elabftw/chem-plugin:${{ github.ref_name }}
