name: Release OpenAPI asset
on:
  release:
    types: [published]

jobs:
  upload-openapi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: apidoc/v2/openapi.yaml
