<?php

/**
 * @author Nicolas CARPi / Deltablot
 * @copyright 2026 Nicolas CARPi
 * @see https://www.elabftw.net Official website
 * @license AGPL-3.0
 * @package elabftw
 */

declare(strict_types=1);

namespace Elabftw\Elabftw;

use function bin2hex;
use function preg_match;
use function random_bytes;
use function dirname;
use function file_put_contents;
use function getenv;

$version = getenv('ELABFTW_VERSION') ?: 'dev';

// version int format is used to compare with last_seen_version of users
// major is untouched, and minor and patch are padded with one 0 each
// we should be pretty safe from ever reaching 100 as a minor or patch version!

$versionInt = 0;
if (preg_match('/^(\d+)\.(\d+)\.(\d+)(?:-(alpha|beta|rc)\d*)?$/', $version, $m)) {
    $versionInt = ((int) $m[1]) * 10000 + ((int) $m[2]) * 100 + (int) $m[3];
}

$id = bin2hex(random_bytes(4));

$content = <<<PHP
    <?php

    declare(strict_types=1);

    // DO NOT EDIT: This file is generated by src/tools/mkbuildinfo.php

    namespace Elabftw\Elabftw;

    final class BuildInfo
    {
        public const string ID = '{$id}';

        public const string VERSION = '{$version}';

        public const int VERSION_INT = {$versionInt};
    }
    PHP;

file_put_contents(dirname(__DIR__) . '/Elabftw/BuildInfo.php', $content . "\n");
